### ISSUE TITLE
[Suggestion] Folder search button, Python Optimize button

### ISSUE THREAD

**Issue by PyICoder** [brentvollebregt/auto-py-to-exe#142]
For the output directory, it will be easier to have a folder search button to get the output directory instead of  manually getting the path.

Add options for 

> python -O -m pyinstaller
> python -OO -m pyinstaller
> set PYTHONOPTIMIZE && pyinstaller

as seen [**here**](https://pyinstaller.readthedocs.io/en/stable/usage.html#running-pyinstaller-with-python-optimizations) on the wiki.

**Comment by brentvollebregt** [comment]
I have just put a change into develop which adds browse functionality for the output folder - give it a check for me and tell me if it's what you were looking for.

In regards to the optimisation flags, this project calls PyInstaller by importing it. This means you will need to set the optimise flags when calling auto-py-to-exe for builds to be optimised.

**Comment by PyICoder** [comment]
The output browse button is perfect, for the optimize flags I directly change the default arguments for auto-py-to-exe, but having a option for the optimize flags in the sections of the other PyInstaller options would be great.

**Comment by brentvollebregt** [comment]
For what I see, you are asking to set the compiler optimize flag on at runtime. Unfortunately, this is not possible because the compiler is already running. 

One thing the optimise flag does is remove assert calls. Here are a few steps you can perform to see this and how it will not work setting it in runtime:

1. Create a new Python script containing the following:
    ```python
    print('Start')
    
    try:
        assert 1 == 2, 'A forced error'
        print('No error')
    except AssertionError:
        print('Error')
    
    print('End')
    input()
    ```
2. Open up auto-py-to-exe normally.
3. Package this script normally using auto-py-to-exe, when you run the exe, you will see that the `assert` statement ran (it will output "Error")
4. Close auto-py-to-exe
5. Open a terminal in the root directory of a local clone of this repo and execute `python -O -m auto_py_to_exe` - this will start auto-py-to-exe with optimisations on.
6. Package this script again and run it. This time you will see that the `assert` statement didn't run (it will output "No error"). This proves optimisations are on.
7. Close auto-py-to-exe
8. Go into auto_py_to_exe/packaging.py and add `os.environ['PYTHONOPTIMIZE'] = '1'` on line 96 (after the doc string)
    ```diff
    def package(pyinstaller_command, options):
        """
        Call PyInstaller to package a script using provided arguments and options.
        :param pyinstaller_command: Command to supply to PyInstaller
        :param options: auto-py-to-exe specific options for setup and cleaning up
        :return: Whether packaging was successful
        """

    +    os.environ['PYTHONOPTIMIZE'] = '1'

        # Show current version
        logger.info("Running auto-py-to-exe v" + version)
    ```
9. Execute `python -m auto_py_to_exe` in the same directory as before - this will start auto-py-to-exe with optimisations off; we want it to be set internally by the application.
10. Package this script again and run it. You will see that the `assert` statement did (it will output "Error"). This proves optimisations have not been turned on.

Pretty much you need to enable optimisations on application start or not at all - you can not turn it on during runtime as the compiler is already running and has passed its config setup stage.

**Comment by PyICoder** [comment]
I understand, but it is possible to change these into options in the gui, correct?

**Comment by brentvollebregt** [comment]
No, that is what the above exercise was proving - that you _cannot_ do that.

I call PyInstaller by importing it, not using the cli.

**Comment by PyICoder** [comment]
Ah okay, thanks.

**Comment by brentvollebregt** [comment]
A build is running now to release the browse button - it will be under 2.7.10 and should take about 10min.
