### ISSUE TITLE
use auto-py-to-exe in Chinese

### ISSUE THREAD

**Issue by jiangzhe11** [brentvollebregt/auto-py-to-exe#153]
In order to use it more conveniently as a Chinese, I translated it into Chinese. [this](https://github.com/jiangzhe11/auto-py-to-exe-in-Chinese)
I suggest that you make users from different countries into consideration and provide different language versions.
Thanks very much!

**Comment by brentvollebregt** [comment]
I would be happy to add translations, but there is an issue with this. A lot of the content in the UI is automatically extracted from PyInstaller itself at run time. This means either:
- We only translate the static text in the application (I think this is what you have done in constants.js and index.html)
- We translate the static stuff noted above and translate all the dynamic text using replacements (full sentences/paragraphs, not words). We will need to update these for each change PyInstaller does (which isn't very often at the moment).

**Comment by jiangzhe11** [comment]
That's true.
However, maybe translations in the static text is enough for some basic things. Although it's not perfect, but it helps users a lot.
Thanks for reply.

**Comment by brentvollebregt** [comment]
Sounds fair.

I was thinking about this and remembered Chrome has a translate feature. Since this app runs in Chrome's App mode by default, you could use its translation feature:

![image](https://user-images.githubusercontent.com/19944838/106379909-0a4eec00-6414-11eb-8e78-5f5338b68679.png)

And if you want to translate to a different language that is not the default:

![image](https://user-images.githubusercontent.com/19944838/106379932-31a5b900-6414-11eb-9626-6d2ce79de535.png)

Here is the result for me:

![image](https://user-images.githubusercontent.com/19944838/106379846-99a7cf80-6413-11eb-8070-a19dbc05bab8.png)

Would this be sufficient or are we trying to cover a different case?

**Comment by jiangzhe11** [comment]
It's a good choice. Although machine translator can not do better than human, it's enough for most of time.

**Comment by brentvollebregt** [comment]
I only know English, so I'm not awfully familiar with machine translations being sub-par - but I can understand that it could be not great.

I am happy to add support for other languages (firstly being Chinese). I'll aim to do:
- All the static text in the UI
- The README

I'll set up a framework in the application for changing languages, add Chinese using your repository and then get you to review if that is ok?

**Comment by jiangzhe11** [comment]
Of course. I feel very honored for that.

**Comment by jiangzhe11** [comment]
I added README translation and pulled request.
#154

**Comment by brentvollebregt** [comment]
This is now in master and has been released to PyPI under 2.8.0.
Thank you very much @jiangzhe11 for your assistance - I appreciate it.
