### ISSUE TITLE
Antivirus reports exe as threat

### ISSUE THREAD

**Issue by dpanayotakopoulos** [brentvollebregt/auto-py-to-exe#16]
Hi.

Excellent job. An issue:

I was practicing with python and PySide.
When I created a standalone exe (option: One File) there was no problem with Norton Security.
However, when I used the option: One Directory, Norton removed the exe from the output folder. I recovered it and I uploaded it to https://www.virustotal.com to see how the other antivirus programs act.
Here is the virus total report: https://www.virustotal.com/#/file/2d0a81ec73e1e7e571d972f1e11992cebc22e06edf17a7614fb37cdd0cf5ed93/detection.

I am pretty sure that there is no problem, but why does this happen? 
Obviously, if I give a copy of the program to someone else, he's antivirus might deleted it.

**Comment by brentvollebregt** [comment]
Since this project simply passes arguments to pyinstaller, it does not have a direct influence on the output package. 

As there are people out there that use pyinstaller for malicious purposes, some parts of the output packages will be constant which can lead to false positives in virus detection by particular software.

The only people that can stop this from occurring are the antivirus vendors themselves, did you submit a ticket to them? There is nothing I or pyinstaller can do about false positives.
If you haven't contacted the antivirus vendors and given samples then I recommend doing so if this is a serious issue.
