### ISSUE TITLE
Error during packaging when arguments are manually provided

### ISSUE THREAD

**Issue by UcanLahana** [brentvollebregt/auto-py-to-exe#172]
I'm getting error while trying to add Manual Argumant Inputs
OUTPUT:
Running auto-py-to-exe v2.9.0

Building directory: C:\Users\KAAN\AppData\Local\Temp\tmpj3fo6bxs

Provided command: pyinstaller --noconfirm --onedir --windowed --add-data "C:/Users/KAAN/Desktop/People-Counting-in-Real-Time-master/videos;videos/" --add-data "C:/Users/KAAN/Desktop/People-Counting-in-Real-Time-master/mylib;mylib/" --add-data "C:/Users/KAAN/Desktop/People-Counting-in-Real-Time-master/mobilenet_ssd;mobilenet_ssd/" --input C:/Users/KAAN/Desktop/EXE/videos/example_01.mp4 "C:/Users/KAAN/Desktop/People-Counting-in-Real-Time-master/Run.py"

Recursion Limit is set to 5000

Executing: pyinstaller --noconfirm --onedir --windowed --add-data C:/Users/KAAN/Desktop/People-Counting-in-Real-Time-master/videos;videos/ --add-data C:/Users/KAAN/Desktop/People-Counting-in-Real-Time-master/mylib;mylib/ --add-data C:/Users/KAAN/Desktop/People-Counting-in-Real-Time-master/mobilenet_ssd;mobilenet_ssd/ --input C:/Users/KAAN/Desktop/EXE/videos/example_01.mp4 C:/Users/KAAN/Desktop/People-Counting-in-Real-Time-master/Run.py --distpath C:\Users\KAAN\AppData\Local\Temp\tmpj3fo6bxs\application --workpath C:\Users\KAAN\AppData\Local\Temp\tmpj3fo6bxs\build --specpath C:\Users\KAAN\AppData\Local\Temp\tmpj3fo6bxs

An error occurred while packaging
Traceback (most recent call last):
  File "d:\anaconda3\envs\webscrape\lib\site-packages\auto_py_to_exe\packaging.py", line 131, in package
    run_pyinstaller()
  File "d:\anaconda3\envs\webscrape\lib\site-packages\PyInstaller\__main__.py", line 96, in run
    args = parser.parse_args(pyi_args)
  File "d:\anaconda3\envs\webscrape\lib\argparse.py", line 1737, in parse_args
    self.error(msg % ' '.join(argv))
  File "d:\anaconda3\envs\webscrape\lib\argparse.py", line 2393, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "d:\anaconda3\envs\webscrape\lib\argparse.py", line 2380, in exit
    _sys.exit(status)
SystemExit: 2

Project output will not be moved to output folder

Complete.

**Comment by brentvollebregt** [comment]
With it failing in `argparse.py`, I am guessing it is an argument parsing error.

I see you are using `--input VAL`, which is not a PyInstaller option as far as I am aware.

**Comment by UcanLahana** [comment]
I'm getting this OUTPUT without --input VAL:

Running auto-py-to-exe v2.9.0

Building directory: C:\Users\KAAN\AppData\Local\Temp\tmpestwbuu3

Provided command: pyinstaller --noconfirm --onedir --windowed --add-data "C:/Users/KAAN/Desktop/People-Counting-in-Real-Time-master/mylib;mylib/" --add-data "C:/Users/KAAN/Desktop/People-Counting-in-Real-Time-master/mobilenet_ssd;mobilenet_ssd/" --add-data "C:/Users/KAAN/Desktop/People-Counting-in-Real-Time-master/videos;videos/" --prototxt mobilenet_ssd/MobileNetSSD_deploy.prototxt --model mobilenet_ssd/MobileNetSSD_deploy.caffemodel "C:/Users/KAAN/Desktop/People-Counting-in-Real-Time-master/Run.py"

Recursion Limit is set to 5000

Executing: pyinstaller --noconfirm --onedir --windowed --add-data C:/Users/KAAN/Desktop/People-Counting-in-Real-Time-master/mylib;mylib/ --add-data C:/Users/KAAN/Desktop/People-Counting-in-Real-Time-master/mobilenet_ssd;mobilenet_ssd/ --add-data C:/Users/KAAN/Desktop/People-Counting-in-Real-Time-master/videos;videos/ --prototxt mobilenet_ssd/MobileNetSSD_deploy.prototxt --model mobilenet_ssd/MobileNetSSD_deploy.caffemodel C:/Users/KAAN/Desktop/People-Counting-in-Real-Time-master/Run.py --distpath C:\Users\KAAN\AppData\Local\Temp\tmpestwbuu3\application --workpath C:\Users\KAAN\AppData\Local\Temp\tmpestwbuu3\build --specpath C:\Users\KAAN\AppData\Local\Temp\tmpestwbuu3



An error occurred while packaging
Traceback (most recent call last):
  File "d:\anaconda3\envs\webscrape\lib\site-packages\auto_py_to_exe\packaging.py", line 131, in package
    run_pyinstaller()
  File "d:\anaconda3\envs\webscrape\lib\site-packages\PyInstaller\__main__.py", line 96, in run
    args = parser.parse_args(pyi_args)
  File "d:\anaconda3\envs\webscrape\lib\argparse.py", line 1737, in parse_args
    self.error(msg % ' '.join(argv))
  File "d:\anaconda3\envs\webscrape\lib\argparse.py", line 2393, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "d:\anaconda3\envs\webscrape\lib\argparse.py", line 2380, in exit
    _sys.exit(status)
SystemExit: 2



Project output will not be moved to output folder

Complete.

**Comment by brentvollebregt** [comment]
Again, I see you're using `--prototxt VAL` and `--model VAL` which are neither [PyInstaller options](https://pyinstaller.readthedocs.io/en/stable/usage.html) as far as I am aware.

Please only add PyInstaller options here.

**Comment by UcanLahana** [comment]
I got it now. I have to add this script options some where. Can you help me about it ? This is project https://github.com/saimj7/People-Counting-in-Real-Time that I have to make it executable. Thanks for your patience.

**Comment by brentvollebregt** [comment]
The input you are using is an escape hatch for situations where the tool cannot provide all the options you want during the packaging process. 

Why are you providing them when packaging? Potentially these arguments you are adding should be provided at runtime?

**Comment by UcanLahana** [comment]
I don't know but i searched more project about people counting. They were same runtime inputs that you have to indicate these options. Maybe i should try another ways like config file or insert to script.

**Comment by brentvollebregt** [comment]
I feel like you should be passing those arguments when running the executable. I imagine you provide them when you run your Python script - this will be the same.

**Comment by knguyen1401** [comment]
Try an older version idk

**Comment by knguyen1401** [comment]
Help me with this

Running auto-py-to-exe v2.8.0
Building directory: C:\Users\KNGUY~1.DES\AppData\Local\Temp\tmpmzcdc1wm
Provided command: pyinstaller --noconfirm --onefile --windowed --icon "C:/Program Files/SCP/SCPicon.ico"  "C:/Users/knguy.DESKTOP-HK64HD9/Documents/SCP/SCP-106.py"
Recursion Limit is set to 5000
Executing: pyinstaller --noconfirm --onefile --windowed --icon C:/Program Files/SCP/SCPicon.ico C:/Users/knguy.DESKTOP-HK64HD9/Documents/SCP/SCP-106.py --distpath C:\Users\KNGUY~1.DES\AppData\Local\Temp\tmpmzcdc1wm\application --workpath C:\Users\KNGUY~1.DES\AppData\Local\Temp\tmpmzcdc1wm\build --specpath C:\Users\KNGUY~1.DES\AppData\Local\Temp\tmpmzcdc1wm

26086 INFO: PyInstaller: 4.3
26092 INFO: Python: 3.9.4
26100 INFO: Platform: Windows-10-10.0.19041-SP0
26111 INFO: wrote C:\Users\KNGUY~1.DES\AppData\Local\Temp\tmpmzcdc1wm\SCP-106.spec
26163 INFO: UPX is not available.
26219 INFO: Extending PYTHONPATH with paths
['C:\\Users\\knguy.DESKTOP-HK64HD9\\Documents\\SCP',
 'C:\\Users\\KNGUY~1.DES\\AppData\\Local\\Temp\\tmpmzcdc1wm']
26261 INFO: checking Analysis
26268 INFO: Building Analysis because Analysis-00.toc is non existent
26284 INFO: Initializing module dependency graph...
26312 INFO: Caching module graph hooks...
26341 WARNING: Several hooks defined for module 'win32ctypes.core'. Please take care they do not conflict.
26366 INFO: Analyzing base_library.zip ...
32092 INFO: Processing pre-find module path hook distutils from 'C:\\Users\\knguy.DESKTOP-HK64HD9\\AppData\\Roaming\\Python\\Python39\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
32099 INFO: distutils: retargeting to non-venv dir 'C:\\Program Files\\Python39\\lib'
36985 INFO: Caching module dependency graph...
37475 INFO: running Analysis Analysis-00.toc
37525 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Program Files\Python39\python.exe
37654 WARNING: lib not found: api-ms-win-core-path-l1-1-0.dll dependency of C:\Program Files\Python39\python39.dll
37699 INFO: Analyzing C:\Users\knguy.DESKTOP-HK64HD9\Documents\SCP\SCP-106.py
37778 INFO: Processing module hooks...
37783 INFO: Loading module hook 'hook-difflib.py' from 'C:\\Users\\knguy.DESKTOP-HK64HD9\\AppData\\Roaming\\Python\\Python39\\site-packages\\PyInstaller\\hooks'...
37800 INFO: Loading module hook 'hook-distutils.py' from 'C:\\Users\\knguy.DESKTOP-HK64HD9\\AppData\\Roaming\\Python\\Python39\\site-packages\\PyInstaller\\hooks'...
37814 INFO: Loading module hook 'hook-distutils.util.py' from 'C:\\Users\\knguy.DESKTOP-HK64HD9\\AppData\\Roaming\\Python\\Python39\\site-packages\\PyInstaller\\hooks'...
37825 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Users\\knguy.DESKTOP-HK64HD9\\AppData\\Roaming\\Python\\Python39\\site-packages\\PyInstaller\\hooks'...
38010 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Users\\knguy.DESKTOP-HK64HD9\\AppData\\Roaming\\Python\\Python39\\site-packages\\PyInstaller\\hooks'...
38018 INFO: Loading module hook 'hook-lib2to3.py' from 'C:\\Users\\knguy.DESKTOP-HK64HD9\\AppData\\Roaming\\Python\\Python39\\site-packages\\PyInstaller\\hooks'...
38318 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'C:\\Users\\knguy.DESKTOP-HK64HD9\\AppData\\Roaming\\Python\\Python39\\site-packages\\PyInstaller\\hooks'...
38328 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Users\\knguy.DESKTOP-HK64HD9\\AppData\\Roaming\\Python\\Python39\\site-packages\\PyInstaller\\hooks'...
38338 INFO: Loading module hook 'hook-PyQt5.py' from 'C:\\Users\\knguy.DESKTOP-HK64HD9\\AppData\\Roaming\\Python\\Python39\\site-packages\\PyInstaller\\hooks'...
38777 WARNING: Hidden import "sip" not found!
38783 INFO: Loading module hook 'hook-PyQt5.QtCore.py' from 'C:\\Users\\knguy.DESKTOP-HK64HD9\\AppData\\Roaming\\Python\\Python39\\site-packages\\PyInstaller\\hooks'...
38993 INFO: Loading module hook 'hook-PyQt5.QtGui.py' from 'C:\\Users\\knguy.DESKTOP-HK64HD9\\AppData\\Roaming\\Python\\Python39\\site-packages\\PyInstaller\\hooks'...
39318 INFO: Loading module hook 'hook-PyQt5.QtWebEngineWidgets.py' from 'C:\\Users\\knguy.DESKTOP-HK64HD9\\AppData\\Roaming\\Python\\Python39\\site-packages\\PyInstaller\\hooks'...
40666 INFO: Loading module hook 'hook-PyQt5.QtWidgets.py' from 'C:\\Users\\knguy.DESKTOP-HK64HD9\\AppData\\Roaming\\Python\\Python39\\site-packages\\PyInstaller\\hooks'...
41261 INFO: Loading module hook 'hook-sysconfig.py' from 'C:\\Users\\knguy.DESKTOP-HK64HD9\\AppData\\Roaming\\Python\\Python39\\site-packages\\PyInstaller\\hooks'...
41268 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'C:\\Users\\knguy.DESKTOP-HK64HD9\\AppData\\Roaming\\Python\\Python39\\site-packages\\PyInstaller\\hooks'...
41279 INFO: Loading module hook 'hook-xml.py' from 'C:\\Users\\knguy.DESKTOP-HK64HD9\\AppData\\Roaming\\Python\\Python39\\site-packages\\PyInstaller\\hooks'...
41436 INFO: Loading module hook 'hook-_tkinter.py' from 'C:\\Users\\knguy.DESKTOP-HK64HD9\\AppData\\Roaming\\Python\\Python39\\site-packages\\PyInstaller\\hooks'...
41778 INFO: checking Tree
41784 INFO: Building Tree because Tree-00.toc is non existent
41792 INFO: Building Tree Tree-00.toc
41955 INFO: checking Tree
41962 INFO: Building Tree because Tree-01.toc is non existent
41972 INFO: Building Tree Tree-01.toc
42196 INFO: checking Tree
42202 INFO: Building Tree because Tree-02.toc is non existent
42211 INFO: Building Tree Tree-02.toc
42245 INFO: Loading module hook 'hook-PyQt5.QtNetwork.py' from 'C:\\Users\\knguy.DESKTOP-HK64HD9\\AppData\\Roaming\\Python\\Python39\\site-packages\\PyInstaller\\hooks'...
42722 INFO: Loading module hook 'hook-PyQt5.QtPrintSupport.py' from 'C:\\Users\\knguy.DESKTOP-HK64HD9\\AppData\\Roaming\\Python\\Python39\\site-packages\\PyInstaller\\hooks'...
43349 INFO: Loading module hook 'hook-PyQt5.QtQml.py' from 'C:\\Users\\knguy.DESKTOP-HK64HD9\\AppData\\Roaming\\Python\\Python39\\site-packages\\PyInstaller\\hooks'...
44193 INFO: Loading module hook 'hook-PyQt5.QtQuick.py' from 'C:\\Users\\knguy.DESKTOP-HK64HD9\\AppData\\Roaming\\Python\\Python39\\site-packages\\PyInstaller\\hooks'...
45082 INFO: Loading module hook 'hook-PyQt5.QtQuickWidgets.py' from 'C:\\Users\\knguy.DESKTOP-HK64HD9\\AppData\\Roaming\\Python\\Python39\\site-packages\\PyInstaller\\hooks'...
46228 INFO: Looking for ctypes DLLs
46303 INFO: Analyzing run-time hooks ...
46317 INFO: Including run-time hook 'C:\\Users\\knguy.DESKTOP-HK64HD9\\AppData\\Roaming\\Python\\Python39\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
46330 INFO: Including run-time hook 'C:\\Users\\knguy.DESKTOP-HK64HD9\\AppData\\Roaming\\Python\\Python39\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pyqt5webengine.py'
46340 INFO: Including run-time hook 'C:\\Users\\knguy.DESKTOP-HK64HD9\\AppData\\Roaming\\Python\\Python39\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pyqt5.py'
46357 INFO: Looking for dynamic libraries
46545 WARNING: lib not found: api-ms-win-core-winrt-l1-1-0.dll dependency of C:\Users\knguy.DESKTOP-HK64HD9\AppData\Roaming\Python\Python39\site-packages\PyQt5\Qt5\plugins\position\qtposition_winrt.dll
46554 WARNING: lib not found: api-ms-win-core-winrt-string-l1-1-0.dll dependency of C:\Users\knguy.DESKTOP-HK64HD9\AppData\Roaming\Python\Python39\site-packages\PyQt5\Qt5\plugins\position\qtposition_winrt.dll
47085 WARNING: lib not found: Qt53DCore.dll dependency of C:\Users\knguy.DESKTOP-HK64HD9\AppData\Roaming\Python\Python39\site-packages\PyQt5\Qt5\qml\QtQuick\Scene3D\qtquickscene3dplugin.dll
47096 WARNING: lib not found: Qt53DAnimation.dll dependency of C:\Users\knguy.DESKTOP-HK64HD9\AppData\Roaming\Python\Python39\site-packages\PyQt5\Qt5\qml\QtQuick\Scene3D\qtquickscene3dplugin.dll
47114 WARNING: lib not found: Qt53DLogic.dll dependency of C:\Users\knguy.DESKTOP-HK64HD9\AppData\Roaming\Python\Python39\site-packages\PyQt5\Qt5\qml\QtQuick\Scene3D\qtquickscene3dplugin.dll
47129 WARNING: lib not found: Qt53DRender.dll dependency of C:\Users\knguy.DESKTOP-HK64HD9\AppData\Roaming\Python\Python39\site-packages\PyQt5\Qt5\qml\QtQuick\Scene3D\qtquickscene3dplugin.dll
47154 WARNING: lib not found: Qt53DInput.dll dependency of C:\Users\knguy.DESKTOP-HK64HD9\AppData\Roaming\Python\Python39\site-packages\PyQt5\Qt5\qml\QtQuick\Scene3D\qtquickscene3dplugin.dll
48902 WARNING: lib not found: Qt5MultimediaQuick.dll dependency of C:\Users\knguy.DESKTOP-HK64HD9\AppData\Roaming\Python\Python39\site-packages\PyQt5\Qt5\qml\QtMultimedia\declarative_multimedia.dll
49539 WARNING: lib not found: Qt53DQuickScene2D.dll dependency of C:\Users\knguy.DESKTOP-HK64HD9\AppData\Roaming\Python\Python39\site-packages\PyQt5\Qt5\qml\QtQuick\Scene2D\qtquickscene2dplugin.dll
49564 WARNING: lib not found: Qt53DCore.dll dependency of C:\Users\knguy.DESKTOP-HK64HD9\AppData\Roaming\Python\Python39\site-packages\PyQt5\Qt5\qml\QtQuick\Scene2D\qtquickscene2dplugin.dll
49583 WARNING: lib not found: Qt53DRender.dll dependency of C:\Users\knguy.DESKTOP-HK64HD9\AppData\Roaming\Python\Python39\site-packages\PyQt5\Qt5\qml\QtQuick\Scene2D\qtquickscene2dplugin.dll
51883 WARNING: lib not found: api-ms-win-core-winrt-l1-1-0.dll dependency of C:\Users\knguy.DESKTOP-HK64HD9\AppData\Roaming\Python\Python39\site-packages\PyQt5\Qt5\bin\Qt5Bluetooth.dll
51895 WARNING: lib not found: api-ms-win-core-winrt-string-l1-1-0.dll dependency of C:\Users\knguy.DESKTOP-HK64HD9\AppData\Roaming\Python\Python39\site-packages\PyQt5\Qt5\bin\Qt5Bluetooth.dll
52753 INFO: Looking for eggs
52760 INFO: Using Python library C:\Program Files\Python39\python39.dll
52775 INFO: Found binding redirects: 
[]
52801 INFO: Warnings written to C:\Users\KNGUY~1.DES\AppData\Local\Temp\tmpmzcdc1wm\build\SCP-106\warn-SCP-106.txt
52937 INFO: Graph cross-reference written to C:\Users\KNGUY~1.DES\AppData\Local\Temp\tmpmzcdc1wm\build\SCP-106\xref-SCP-106.html
53100 INFO: checking PYZ
53115 INFO: Building PYZ because PYZ-00.toc is non existent
53129 INFO: Building PYZ (ZlibArchive) C:\Users\KNGUY~1.DES\AppData\Local\Temp\tmpmzcdc1wm\build\SCP-106\PYZ-00.pyz
54424 INFO: Building PYZ (ZlibArchive) C:\Users\KNGUY~1.DES\AppData\Local\Temp\tmpmzcdc1wm\build\SCP-106\PYZ-00.pyz completed successfully.
54490 INFO: checking PKG
54501 INFO: Building PKG because PKG-00.toc is non existent
54516 INFO: Building PKG (CArchive) PKG-00.pkg
112375 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
112553 INFO: Bootloader C:\Users\knguy.DESKTOP-HK64HD9\AppData\Roaming\Python\Python39\site-packages\PyInstaller\bootloader\Windows-64bit\runw.exe
112565 INFO: checking EXE
112574 INFO: Building EXE because EXE-00.toc is non existent
112597 INFO: Building EXE from EXE-00.toc
112619 INFO: Copying icons from ['C:\\Program Files\\SCP\\SCPicon.ico']
An error occurred while packaging
Traceback (most recent call last):
  File "D:\auto-py-to-exe-2.8.0\auto_py_to_exe\packaging.py", line 131, in package
    run_pyinstaller()
  File "C:\Users\knguy.DESKTOP-HK64HD9\AppData\Roaming\Python\Python39\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\knguy.DESKTOP-HK64HD9\AppData\Roaming\Python\Python39\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\knguy.DESKTOP-HK64HD9\AppData\Roaming\Python\Python39\site-packages\PyInstaller\building\build_main.py", line 737, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Users\knguy.DESKTOP-HK64HD9\AppData\Roaming\Python\Python39\site-packages\PyInstaller\building\build_main.py", line 684, in build
    exec(code, spec_namespace)
  File "C:\Users\KNGUY~1.DES\AppData\Local\Temp\tmpmzcdc1wm\SCP-106.spec", line 21, in <module>
    exe = EXE(pyz,
  File "C:\Users\knguy.DESKTOP-HK64HD9\AppData\Roaming\Python\Python39\site-packages\PyInstaller\building\api.py", line 450, in __init__
    self.__postinit__()
  File "C:\Users\knguy.DESKTOP-HK64HD9\AppData\Roaming\Python\Python39\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
    self.assemble()
  File "C:\Users\knguy.DESKTOP-HK64HD9\AppData\Roaming\Python\Python39\site-packages\PyInstaller\building\api.py", line 549, in assemble
    icon.CopyIcons(tmpnm, self.icon)
  File "C:\Users\knguy.DESKTOP-HK64HD9\AppData\Roaming\Python\Python39\site-packages\PyInstaller\utils\win32\icon.py", line 216, in CopyIcons
    return CopyIcons_FromIco(dstpath, [srcpath])
  File "C:\Users\knguy.DESKTOP-HK64HD9\AppData\Roaming\Python\Python39\site-packages\PyInstaller\utils\win32\icon.py", line 153, in CopyIcons_FromIco
    for i, f in enumerate(icons):
  File "C:\Users\knguy.DESKTOP-HK64HD9\AppData\Roaming\Python\Python39\site-packages\PyInstaller\utils\win32\icon.py", line 117, in __init__
    entry.fromfile(file)
  File "C:\Users\knguy.DESKTOP-HK64HD9\AppData\Roaming\Python\Python39\site-packages\PyInstaller\utils\win32\icon.py", line 76, in fromfile
    self._fields_ = list(struct.unpack(self._format_, data))
struct.error: unpack requires a buffer of 16 bytes

Project output will not be moved to output folder
Complete.

**Comment by brentvollebregt** [comment]
@knguyen1401 is your error related to the original issue here? It definitely looks different. 

Could you please create a new issue if you want to raise a bug. Also remember these are GitHub issues, not a place to tell people to help you.

**Comment by knguyen1401** [comment]
@brentvollebregt Well, I try to put the icon to the app and get the error. If I don't put the icon, I won't receive that error anymore. I'll try Process Hacker to change the icon

**Comment by knguyen1401** [comment]
I think it is a memory issue idk

**Comment by brentvollebregt** [comment]
@knguyen1401 create a new issue for your problem. 
It is not related to the issue in this ticket.

**Comment by knguyen1401** [comment]
I solved it
