### ISSUE TITLE
Failed to determine matplotlib's data directory!

### ISSUE THREAD

**Issue by pedrobele** [brentvollebregt/auto-py-to-exe#248]
Hello,

I have this error... my code (py) is very simple, only for testing...

import numpy as np
print('teste...')

  File "C:\Anaconda3\lib\site-packages\pyinstaller-4.9-py3.9-win-amd64.egg\PyInstaller\hooks\hook-matplotlib.py", line 15, in <module>
    assert mpl_data_dir, "Failed to determine matplotlib's data directory!"
AssertionError: Failed to determine matplotlib's data directory!

Any ideias?

**Comment by brentvollebregt** [comment]
Two issues here:

1. PyInstaller is trying to include matplotlib even though it's not being used
2. matplotlib's data directory has not been added

Since you are not using matplotlib, we can ignore 2 when solving 1. My recommendation is to use a virtual environment that contains only the libraries you need and auto-py-to-exe - make sure to run auto-py-to-exe from this virtual environment and not the environment containing all the other packages.
