### ISSUE TITLE
Eel requirement is old

### ISSUE THREAD

**Issue by gjf** [brentvollebregt/auto-py-to-exe#261]
> auto-py-to-exe 2.18.1 requires Eel==0.12.4, but you have eel 0.14.0 which is incompatible.

I see this message every time - is it really crytitcal for auto-py-to-exe to have an obsolete eel version?

**Comment by brentvollebregt** [comment]
The reason I have fixed the Eel version is because I've seen the maintainer change things in the library which broke this project - see https://github.com/brentvollebregt/auto-py-to-exe/commit/3a08aeaa8b9eeae950cee9cd5f1bda168c7077cf. I would like to say any version above x but we are using things in this project that may break in the future.

I've just bumped the Eel version to the latest and it will be released under 2.18.2 soon
