### ISSUE TITLE
which autopy version is compatible with python 3.10

### ISSUE THREAD

**Issue by Neeraj-Shilwant** [brentvollebregt/auto-py-to-exe#265]
how to install autopy because i am getting errors

**Comment by brentvollebregt** [comment]
The latest version of auto-py-to-exe is compatible with python 3.10

**Comment by neek8044** [comment]
If you are having trouble installing, try running: `pip install auto-py-to-exe` or if you have downloaded the release file already try: `pip install "C:/path/to/the/file/auto_py_to_exe-version-py2.py3-none-any.whl"`. Make sure the path is in quotation marks and change `version` to the version number you downloaded. If that still doesn't work, try again with `pip3` instead of `pip`.
