### ISSUE TITLE
Exe

### ISSUE THREAD

**Issue by Abhijeetbyte** [brentvollebregt/auto-py-to-exe#267]
Can you guys pack this tool into an .exe application ?

Right now I'm using it, as a shortcut profile , it's awesome 👏👏👍👍

Here is some screenshots

![image](https://user-images.githubusercontent.com/80936610/166142607-9ddb67b7-92ac-40fd-95d7-695502aca691.png)

![image](https://user-images.githubusercontent.com/80936610/166142649-79f617ed-b345-453d-a878-e8b0d1b2f023.png)

**Comment by brentvollebregt** [comment]
In #239 I noted that

> there is not an executable version of auto-py-to-exe - if there was, it would be much harder to package third-party packages

Since the exe would be using it's own internal version of Python, you would have to add the `site-packages` folder manually to tell PyInstaller where to look for modules. Even if this was done, you would need to be sure the two versions of Python were the same (the internal one and the one installed globally on the host).
