### ISSUE TITLE
eel.chrome has no attribute get_instance_path error when trying to run the program

### ISSUE THREAD

**Issue by SquidR** [brentvollebregt/auto-py-to-exe#275]
I havent seen anybody have this issue before 

> Traceback (most recent call last):
>   File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,  File "C:\Python38\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)  File "C:\Python38\lib\site-packages\auto_py_to_exe\__main__.py", line 302, in <module>
>     run()  File "C:\Python38\lib\site-packages\auto_py_to_exe\__main__.py", line 291, in run
>     if eel.chrome.get_instance_path() is not None and not disable_chrome:AttributeError: module 'eel.chrome' has no attribute 
> 'get_instance_path'

the command i run is auto-py-to-exe, any help would be greatly appreciated.

**Comment by brentvollebregt** [comment]
What version of Eel do you have installed?

**Comment by SquidR** [comment]
> What version of Eel do you have installed?

v0.14.0

**Comment by brentvollebregt** [comment]
Looking at your traceback,

> File "C:\Python38\lib\site-packages\auto_py_to_exe_main.py", line 302, in
run() File "C:\Python38\lib\site-packages\auto_py_to_exe_main.py", line 291, in run
if eel.chrome.get_instance_path() is not None and not disable_chrome

`main.py` only has 119 lines in it now, and `eel.chrome.get_instance_path` hasn't been referenced since 2.6.6.

What version of auto-py-to-exe are you using? It looks like this was maybe fixed in 2.6.6.
