### ISSUE TITLE
Can anyone help what this error means?

### ISSUE THREAD

**Issue by dev-bot-team** [brentvollebregt/auto-py-to-exe#376]
It was worked couple of days ago now I get this strange error:

![Screenshot 2023-03-10 081044](https://user-images.githubusercontent.com/125034016/224247865-da820c8f-3700-4d1e-86e7-794c2c57c5cd.png)

any help appreciate !

**Comment by brentvollebregt** [comment]
Could you fill in the bug template? (the one you cleared out)

Also, have you validated that this file exists when following the debugging steps? It looks like you are referencing a file that doesn't exist.

**Comment by dev-bot-team** [comment]
When I run the python code in Visual Code it works, then I use Pyinstaller and export EXE and this happens.
No the file doesnt exist there so I copied it there and after tried and still it keeps saying it is not there.
I end up with CMD and BAT file since I dont have fuckign nervs for this shit pyinstaller and exe file
Still it doesnt work and no one care it looks like that shit is creating some PATH which will not work when exporting exe.

**Comment by brentvollebregt** [comment]
Since these are not Python files, you need to add them using the additional files section - have you done this?

This issue is covered under ["FileNotFoundError: [Errno 2] No such file or directory" in the help post](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#filenotfounderror-errno-2-no-such-file-or-directory).
