### ISSUE TITLE
[Question] os.path use inside imported module?

### ISSUE THREAD

**Issue by asd417** [brentvollebregt/auto-py-to-exe#400]
I made a calendar app on python using google api.
It has no problems running but after packaging I get this error.

```
 File "apimanager.py", line 52, in get_service
  File "googleapiclient\_helpers.py", line 130, in positional_wrapper
  File "googleapiclient\discovery.py", line 287, in build
  File "googleapiclient\discovery.py", line 404, in _retrieve_discovery_doc
googleapiclient.errors.UnknownApiNameOrVersion: name: calendar  version: v3
```

So I looked at what the line was doing, it was using this in ``\venv\Lib\site-packages\googleapiclient\discovery_cache\__init__.py``
```
DISCOVERY_DOC_DIR=os.path.join(
    os.path.dirname(os.path.realpath(__file__)), "documents"
)
...
try:
        with open(os.path.join(DISCOVERY_DOC_DIR, doc_name), "r") as f:
            content = f.read()
    except FileNotFoundError:
        # File does not exist. Nothing to do here.
        pass
```
What this tries to do is essentially open bunch of json files inside
``\venv\Lib\site-packages\googleapiclient\discovery_cache\documents``

So I tried to include the folder with --add-data
with ``documents/`` and ``discovery_cache/documents/``
 but it still gives me the same error.

Is there a way to fix this?

**Comment by brentvollebregt** [comment]
Check out [this comment](https://github.com/googleapis/google-api-python-client/issues/876#issuecomment-1586455379) and [this PR](https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/596) - might pay to pick up the changes from that PR and see if it fixes your issues (could use a very recent build of pyinstaller)

**Comment by ArthurKlausHoff** [comment]
This error should be fixed by the PR mentioned above.

You could get it, if you don't want to wait for a new release of the hooks, by installing `pyinstaller-hooks-contrib` directly from git using `pip install --upgrade git+https://github.com/pyinstaller/pyinstaller-hooks-contrib@master` (i only recommend doing this inside a virtual env).

Or you could add static_discovery=False to your call to discovery.build in `apimanager.py`, like:
```python
def get_service(...):
  ...
  discovery.build("calendar", "v3", developerKey="...", static_discovery=False)
  ...
``` 
And remove it when a new release of the hooks comes out.

Just some info. Whit the fix the bundled app might take more time to startup (on onefile mode) or take more space (specially on onedir mode) because discovery_cache has like 459 json files. It is just a waste of space and time in 99.9% of use cases, where it will only use a maximum of 10 different APIs.
