### ISSUE TITLE
Can't find package tkdnd

### ISSUE THREAD

**Issue by AlbertLord** [brentvollebregt/auto-py-to-exe#424]
Before posting I've reviewed issues: [#104 ](https://github.com/brentvollebregt/auto-py-to-exe/issues/104) and [#225 ](https://github.com/brentvollebregt/auto-py-to-exe/issues/225)

I've made an application using the tkinter and tkinterdnd:
```
import tkinter as tk
from tkinter import filedialog
from tkinter import ttk
from tkinterdnd2 import DND_FILES, TkinterDnD
```

Using the PyInstaller code generated by auto-py-to-exe:
`pyinstaller --noconfirm --onefile --windowed  "E:/[REDACTED FOR PRIVACY]/stp_to_xyz_application.py"`

Though the .exe was created successfully, running it gave an error message:

> Traceback (most recent call last):
>   File "tkinterdnd2\TkinterDnD.py", line 53, in _require
> _tkinter.TclError: can't find package tkdnd
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "stp_to_xyz_application.py", line 148, in <module>
>   File "tkinterdnd2\TkinterDnD.py", line 285, in __init__
>   File "tkinterdnd2\TkinterDnD.py", line 55, in _require
> RuntimeError: Unable to load tkdnd library.

After this I tried using the `--hidden-import`  adding `tkdnd` and `tkinterdnd2` to the command:
`pyinstaller --noconfirm --onefile --windowed --hidden-import "tkinterdnd2" --hidden-import "tkdnd"  "E:/[REDACTED]/stp_to_xyz_application.py"`
This resulted in the same error.

Next I've added the paths of the library to the `--paths` :
`pyinstaller --noconfirm --onefile --windowed --hidden-import "tkinterdnd2" --hidden-import "tkdnd" --paths "C:/Users/[REDACTED]/AppData/Local/Programs/Python/Python311/Lib/site-packages/tkdnd" --paths "C:/Users/[REDACTED]/AppData/Local/Programs/Python/Python311/Lib/site-packages/tkinterdnd2"  "E:/[REDACTED]/stp_to_xyz_application.py"`

Same error and I'm out of ideas.

Thank you for any help in advance.

**Comment by brentvollebregt** [comment]
Unfortunately this issue is library-specific so I won't be able to offer a huge amount of help as the issue more lies around how tkinterdnd2 works.

I see [this comment is talking about a PyInstaller hook](https://github.com/pmgagne/tkinterdnd2/issues/7#issuecomment-1481456416), which would have helped identify the missing parts - unfortunately that repo doesn't exist anymore. I just looked inside [that module](https://pypi.org/project/tkinterdnd2-universal) and saw there were a lot of .tcl files - maybe the library you are using also has these .tcl files?

I would recommend trying to add `--collect-all MODULENAME` - this should collect any data files from the package, like the potentially missing .tcl files.

**Comment by AlbertLord** [comment]
Adding `--collect-all tkinterdnd2` seem to resolve the problem.

Playing around a bit, I found that I do not need any `--path` or `--hidden-import`, the following command produced a working application:
`pyinstaller --noconfirm --onefile --windowed --collect-all "tkinterdnd2"  "E:/[REDACTED]/stp_to_xyz_application.py"`

Thank you for your help.
