### ISSUE TITLE
Default program icon

### ISSUE THREAD

**Issue by Nyrroz** [brentvollebregt/auto-py-to-exe#47]
Here is an icon that you could add to the program as a default one. 

[autopytoexeiconByNyrroz.zip](https://github.com/brentvollebregt/auto-py-to-exe/files/2852023/autopytoexeiconByNyrroz.zip)

**Comment by brentvollebregt** [comment]
I love the icon! 

Do you have it in a larger size? If you view an executable with this file in Windows Explorer's "Large Icon" view, it is small compared to other sizes; maybe something around 128x128 might be more ideal? Also it would be good to remove the white background later (I can do that if required).

Also are there any license restrictions on the use of this image?

**Comment by Nyrroz** [comment]
Thanks !  :)

Here is a folder with:
- .png(No bg and size is 2000x2000)
- .png(White bg and size also 2000x2000)
- .icon(128x128 how you asked, White bg 'cause when there is no bg the icon has a black bg and it is really ugly :p)


Nota: If you want I can give you the .psd project.

And there is are license restrictions, use it as you want (Just leave the credits :) )
Of course if you want to give me some money to help me survive the end of the month contact me to:
nyrozzhd.gaming@gmail.com and I'll give you (kindly) my paypal or my btc adress ;D

[IconByNyrroz.zip](https://github.com/brentvollebregt/auto-py-to-exe/files/2855738/IconByNyrroz.zip)

**Comment by brentvollebregt** [comment]
Sorry, I have noticed I never gave an update on this. 

The reason I didn't act with these icons was due to text being in the bottom right. Yes, I know I could have modified it out myself but I felt that would be rude as this is the final form you gave to me.

Also, the mention of funds may have put me off a year ago as this is an open-source project that is free for anyone to use.
