### ISSUE TITLE
The numpy.array_api submodule is still experimental

### ISSUE THREAD

**Issue by Roboxkin** [brentvollebregt/auto-py-to-exe#479]
Hello!
After packaging the application, this error occurs "UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
   __import__(package)", and the application closes.
There is no solution on the Internet.
Does anyone know how this can be solved?
Thank you

**Comment by brentvollebregt** [comment]
> After packaging the application, this error occurs "UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
import(package)"

That is not an error, that is a warning. The real reason the application closes will be due to something else. 

When you followed the debugging section of the help post, what error did you get? Also, it would be great if you could fill out the issue template you cleared - it will provide context needed to give you help.
