### ISSUE TITLE
open browser not Gui app

### ISSUE THREAD

**Issue by Kamoba** [brentvollebregt/auto-py-to-exe#50]
After all requirements installed, when i do:
 `python -m auto_py_to_exe` 
It opens the browser instead of the Gui app as in the video.
and with the browser it doesn't detect my file.

**Comment by Kamoba** [comment]
Ok now see the problem, it open internet explorer which is certainly not my default browser. I copied the link to Firefox and now it works.

**Comment by brentvollebregt** [comment]
If chrome is not installed, this will make a call to the built in webbrowser module which opens the page in the default browser. If no default browser is set, you will be asked to select what browser to open the interface in.

**Comment by Kamoba** [comment]
Yes Chrome is not installed, i use Chrome portable if need. But 100% sure my default brother is Firefox (but Firefox portable!).

**Comment by brentvollebregt** [comment]
If you execute,
```python
import webbrowser
webbrowser.open('https://www.example.com')
```
What occurs?

**Comment by Kamoba** [comment]
I got internet explorer open to https://www.example.com.
I now i now why on my Windows Setting "Default Application" none are set for 'Web browser' so it's why, but all html files are set to openned by Firefox that's what I was referring to, but i see, it's not the same thing.

**Comment by brentvollebregt** [comment]
Right, I had said "default browser" before, not meaning to reference the default application for .html files. This application does not open a HTML file in the browser, it goes to a locally hosted address which then downloads HTML; these are two different things.

Since we've cleared this all up and the application is doing what is expected, I'll close the issue. Feel free to comment if we have missed something.
