### ISSUE TITLE
Missing hint localization

### ISSUE THREAD

**Issue by mcagriaksoy** [brentvollebregt/auto-py-to-exe#512]
Hi Brent,
Today I came with another feature request or possible missing feature.

When I have changed the language of app, I cannot still see the localized hints of fields like attached image below:
![image](https://github.com/user-attachments/assets/1fa5306b-725a-4ad0-b519-2be2197c571e)

**Reason For New Feature**

I think, these hint information localization is also important. I cannot find these kind of informations in source code so that I am suspecting, these coming directly from the "pyinstaller --help". 
So what do you think? Is it possible to add these translated sentences?

**Comment by brentvollebregt** [comment]
This is dynamic content obtained from the PyInstaller CLI - it's read at runtime, thus no reference in this codebase. 

Since this is dynamic content, it makes it a bit harder to translate properly - if PyInstaller changes something (adds, modifies, removes), the translations defined in this application will not immediately reflect the change.

**Comment by brentvollebregt** [comment]
I'll close this for now as it's not planned
