### ISSUE TITLE
wont open

### ISSUE THREAD

**Issue by BetaCyberSec** [brentvollebregt/auto-py-to-exe#68]
nothing opens when i run it im on the windows 10 linux sub system

**Comment by brentvollebregt** [comment]
Do any messages or errors appear?

**Comment by ehsanonline** [comment]
I can not open on windows 10 too. it says:
This app can't run on your PC
To find a version for your PC, check with the software publisher.
the error is looked like this:
https://www.quora.com/How-can-I-correct-this-error-This-app-cant-run-on-your-PC-I-am-using-Windows-10

I tried both 'One file' and 'One folder' options and my app is super simple and works fine on python 3.6.

**Comment by brentvollebregt** [comment]
@BetaCyberSec said he was running it on the Windows 10 Linux subsystem, you @ehsanonline are running it in Windows which is different.

You haven't supplied what you're actually trying so I am going to have to guess you have packaged your script, moved the executable output to a new computer and am trying to run it. When running the executable, this dialog appears saying "This app can’t run on your PC".

In the page that you linked, architecture has been discussed at the top of the first answer. Are you aware what architectures both your machines have? I discuss the problem you are potentially having in the post that is linked in the auto-py-to-exe UI after *every* build under [The exe Doesn't Work on Another Computer﻿](https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#the-exe-doesnt-work-on-another-computer) - I recommend reading this to see if it's your issue.

Aside from this, please make a new issue next time because your issue does not relate to the original issue created by @BetaCyberSec (unless you are using the Windows 10 Linux subsystem and haven't stated it?).

**Comment by ehsanonline** [comment]
Yes you are right, I'm sorry. my bad!

**Comment by brentvollebregt** [comment]
@BetaCyberSec did you get any further on this?

**Comment by brentvollebregt** [comment]
No further information provided. Closing the issue.

**Comment by mytja** [comment]
On Windows you have to run it like this: python -m auto_py_to_exe
